import {Entites} from "./entites";
import {Indice} from "./indice";
import {Poste} from "./poste";
import {StatutPersonnel} from "./statut-personnel";
import {Service} from "./service";

export interface Personnel {
  id: number,
  adresse: string,
  adresseSecondaire: string,
  fullName: string
  civilite: civilite
  dateDeNaissance: Date
  dateExpirationCarteSejour: Date
  dateDebauchage: Date
  dateEmbauchage: Date
  dateRetraite: Date
  debaucher: boolean
  retraiter: boolean
  entite: Entites
  indice: Indice
  matricule: string
  nom: nom
  etatCivil: any
  coordonnee: any
  organismeSocial: any
  posteGeneral: any
  nomContact: string
  nombreEnfant: number,
  numeroCarteSejour: string,
  numeroTechniqueTemporaire: string
  numeroCnss: string
  // --- champs bancaires supprimés ---
  // cleRib?: string
  // codeBanque?: string
  // codeGuichet?: string
  // numeroCompte?: string
  // banque?: any
  // modePaiement?: any
  pieceIdentite: string,
  poste: Poste
  prenom: string
  email: string
  nationalite: nationalitePays,
  paysOrigine: paysOrigines,
  sourceCarteSejour: string
  unite: Unite
  echelon: string
  categorie: string
  prenomContact: string
  referenceComptable: number,
  isSameDayAndMonth: boolean,
  age: number,
  situationMatrimoniale: situationMatrimoniale,
  statutPersonnel: StatutPersonnel
  telephone: number,
  telephoneContact: number
  numeroTelephonePrimaire: number
  numeroTelephoneSecondaire: number
  signature: string
  complement: string
  commune: communeSenegal
  codePostal: string
  codePays: string
  codeInseeCommune: string
  codeDistributionEtranger: string
  chefvisa: boolean
  chefDejaVise: boolean
}

export enum Unite {
  PATS='PATS',
  ENSEIGNANT = 'ENSEIGNANT',
}

export enum communeSenegal {
  Dakar = 'Dakar',
  Pikine = 'Pikine',
  Guédiawaye = 'Guédiawaye',
  Rufisque = 'Rufisque',
  Thiès = 'Thiès',
  Mbour = 'Mbour',
  Kaolack = 'Kaolack',
  Ziguinchor = 'Ziguinchor',
  SaintLouis = 'Saint-Louis',
  Tambacounda = 'Tambacounda',
  Matam = 'Matam',
  Louga = 'Louga',
  Kaffrine = 'Kaffrine',
  Kédougou = 'Kédougou',
  Sédhiou = 'Sédhiou',
  JoalFadiouth = 'Joal-Fadiouth',
  Tivaouane = 'Tivaouane',
  Mbacké = 'Mbacké',
  Tamba = 'Tamba',
  Diourbel = 'Diourbel',
  Kébémer = 'Kébémer',
  Linguère = 'Linguère',
  Vélingara = 'Vélingara',
  Saraya = 'Saraya',
  Bignona = 'Bignona',
  Oussouye = 'Oussouye',
  Foundiougne = 'Foundiougne',
  MédinaYoroFoulah = 'Médina Yoro Foulah',
  Kanel = 'Kanel',
  Salémata = 'Salémata',
  Goudomp = 'Goudomp',
  Dahra = 'Dahra',
  RanérouFélix = 'Ranérou-Félix',
  Pété = 'Pété',
  Mékhé = 'Mékhé',
  Koumpentoum = 'Koumpentoum',
  Bambey = 'Bambey',
  Koungheul = 'Koungheul',
  Ngoudiane = 'Ngoudiane',
  Kaël = 'Kaël',
  Kayar = 'Kayar',
  Kolda = 'Kolda',
}

export enum civilite {
  MONSIEUR = "MONSIEUR",
  MADAME = "MADAME",
  MADEMOISELLE = "MADEMOISELLE",
  DOCTEUR = "DOCTEUR",
  PROFESSEUR = "PROFESSEUR"
}

export enum nom {
  CSS = "CSS",
  IPRES = "IPRES",
}

export enum situationMatrimoniale {
  Célibataire = "Célibataire",
  Veuve = "Veuve",
  Divorcée = "Divorcée",
  Mariée = "Mariée",
  Concubinage = "Concubinage",
  Union_libre = "Union libre",
}

export enum paysOrigines {
  AF = 'Afghanistan',
  AX = 'Åland Islands',
  AL = 'Albania',
  DZ = 'Algeria',
  AS = 'American Samoa',
  AD = 'Andorra',
  AO = 'Angola',
  AI = 'Anguilla',
  AQ = 'Antarctica',
  AG = 'Antigua and Barbuda',
  AR = 'Argentina',
  AM = 'Armenia',
  AW = 'Aruba',
  AU = 'Australia',
  AT = 'Austria',
  AZ = 'Azerbaijan',
  BS = 'Bahamas',
  BH = 'Bahrain',
  BD = 'Bangladesh',
  BB = 'Barbados',
  BY = 'Belarus',
  BE = 'Belgium',
  BZ = 'Belize',
  BJ = 'Benin',
  BM = 'Bermuda',
  BT = 'Bhutan',
  BO = 'Bolivia',
  BQ = 'Bonaire, Sint Eustatius and Saba',
  BA = 'Bosnia and Herzegovina',
  BW = 'Botswana',
  BV = 'Bouvet Island',
  BR = 'Brazil',
  IO = 'British Indian Ocean Territory',
  BN = 'Brunei Darussalam',
  BG = 'Bulgaria',
  BF = 'Burkina Faso',
  BI = 'Burundi',
  CV = 'Cabo Verde',
  KH = 'Cambodia',
  CM = 'Cameroon',
  CA = 'Canada',
  KY = 'Cayman Islands',
  CF = 'Central African Republic',
  TD = 'Chad',
  CL = 'Chile',
  CN = 'China',
  CX = 'Christmas Island',
  CC = 'Cocos Islands',
  CO = 'Colombia',
  KM = 'Comoros',
  CG = 'Congo',
  CD = 'Democratic Republic of the Congo',
  CK = 'Cook Islands',
  CR = 'Costa Rica',
  HR = 'Croatia',
  CU = 'Cuba',
  CW = 'Curaçao',
  CY = 'Cyprus',
  CZ = 'Czech Republic',
  DK = 'Denmark',
  DJ = 'Djibouti',
  DM = 'Dominica',
  DO = 'Dominican Republic',
  EC = 'Ecuador',
  EG = 'Egypt',
  SV = 'El Salvador',
  GQ = 'Equatorial Guinea',
  ER = 'Eritrea',
  EE = 'Estonia',
  ET = 'Ethiopia',
  FK = 'Falkland Islands',
  FO = 'Faroe Islands',
  FJ = 'Fiji',
  FI = 'Finland',
  FR = 'France',
  GF = 'French Guiana',
  PF = 'French Polynesia',
  TF = 'French Southern Territories',
  GA = 'Gabon',
  GM = 'Gambia',
  GE = 'Georgia',
  DE = 'Germany',
  GH = 'Ghana',
  GI = 'Gibraltar',
  GR = 'Greece',
  GL = 'Greenland',
  GD = 'Grenada',
  GP = 'Guadeloupe',
  GU = 'Guam',
  GT = 'Guatemala',
  GG = 'Guernsey',
  GN = 'Guinea',
  GW = 'Guinea-Bissau',
  GY = 'Guyana',
  HT = 'Haiti',
  HM = 'Heard Island and McDonald Islands',
  VA = 'Holy See',
  HN = 'Honduras',
  HK = 'Hong Kong',
  HU = 'Hungary',
  IS = 'Iceland',
  IN = 'India',
  ID = 'Indonesia',
  IR = 'Iran',
  IQ = 'Iraq',
  IE = 'Ireland',
  IM = 'Isle of Man',
  IL = 'Israel',
  IT = 'Italy',
  JM = 'Jamaica',
  JP = 'Japan',
  JE = 'Jersey',
  JO = 'Jordan',
  KZ = 'Kazakhstan',
  KE = 'Kenya',
  KI = 'Kiribati',
  KP = 'North Korea',
  KR = 'South Korea',
  KW = 'Kuwait',
  KG = 'Kyrgyzstan',
  LA = 'Lao People\'s Democratic Republic',
  LV = 'Latvia',
  LB = 'Lebanon',
  LS = 'Lesotho',
  LR = 'Liberia',
  LY = 'Libya',
  LI = 'Liechtenstein',
  LT = 'Lithuania',
  LU = 'Luxembourg',
  MO = 'Macao',
  MK = 'North Macedonia',
  MG = 'Madagascar',
  MW = 'Malawi',
  MY = 'Malaysia',
  MV = 'Maldives',
  ML = 'Mali',
  MT = 'Malta',
  MH = 'Marshall Islands',
  MQ = 'Martinique',
  MR = 'Mauritania',
  MU = 'Mauritius',
  YT = 'Mayotte',
  MX = 'Mexico',
  FM = 'Micronesia',
  MD = 'Moldova',
  MC = 'Monaco',
  MN = 'Mongolia',
  ME = 'Montenegro',
  MS = 'Montserrat',
  MA = 'Morocco',
  MZ = 'Mozambique',
  MM = 'Myanmar',
  NA = 'Namibia',
  NR = 'Nauru',
  NP = 'Nepal',
  NL = 'Netherlands',
  NC = 'New Caledonia',
  NZ = 'New Zealand',
  NI = 'Nicaragua',
  NE = 'Niger',
  NG = 'Nigeria',
  NU = 'Niue',
  NF = 'Norfolk Island',
  MP = 'Northern Mariana Islands',
  NO = 'Norway',
  OM = 'Oman',
  PK = 'Pakistan',
  PW = 'Palau',
  PS = 'State of Palestine',
  PA = 'Panama',
  PG = 'Papua New Guinea',
  PY = 'Paraguay',
  PE = 'Peru',
  PH = 'Philippines',
  PN = 'Pitcairn',
  PL = 'Poland',
  PT = 'Portugal',
  PR = 'Puerto Rico',
  QA = 'Qatar',
  RE = 'Réunion',
  RO = 'Romania',
  RU = 'Russian Federation',
  RW = 'Rwanda',
  BL = 'Saint Barthélemy',
  SH = 'Saint Helena, Ascension and Tristan da Cunha',
  KN = 'Saint Kitts and Nevis',
  LC = 'Saint Lucia',
  MF = 'Saint Martin',
  PM = 'Saint Pierre and Miquelon',
  VC = 'Saint Vincent and the Grenadines',
  WS = 'Samoa',
  SM = 'San Marino',
  ST = 'Sao Tome and Principe',
  SA = 'Saudi Arabia',
  SN = 'Senegal',
  RS = 'Serbia',
  SC = 'Seychelles',
  SL = 'Sierra Leone',
  SG = 'Singapore',
  SX = 'Sint Maarten',
  SK = 'Slovakia',
  SI = 'Slovenia',
  SB = 'Solomon Islands',
  SO = 'Somalia',
  ZA = 'South Africa',
  GS = 'South Georgia and the South Sandwich Islands',
  SS = 'South Sudan',
  ES = 'Spain',
  LK = 'Sri Lanka',
  SD = 'Sudan',
  SR = 'Suriname',
  SJ = 'Svalbard and Jan Mayen',
  SE = 'Sweden',
  CH = 'Switzerland',
  SY = 'Syrian Arab Republic',
  TW = 'Taiwan',
  TJ = 'Tajikistan',
  TZ = 'Tanzania',
  TH = 'Thailand',
  TL = 'Timor-Leste',
  TG = 'Togo',
  TK = 'Tokelau',
  TO = 'Tonga',
  TT = 'Trinidad and Tobago',
  TN = 'Tunisia',
  TR = 'Turkey',
  TM = 'Turkmenistan',
  TC = 'Turks and Caicos Islands',
  TV = 'Tuvalu',
  UG = 'Uganda',
  UA = 'Ukraine',
  AE = 'United Arab Emirates',
  GB = 'United Kingdom',
  US = 'United States',
  UM = 'United States Minor Outlying Islands',
  UY = 'Uruguay',
  UZ = 'Uzbekistan',
  VU = 'Vanuatu',
  VE = 'Venezuela',
  VN = 'Viet Nam',
  VG = 'Virgin Islands (British)',
  VI = 'Virgin Islands (U.S.)',
  WF = 'Wallis and Futuna',
  EH = "Western Sahara",
  YE = "Yemen",
  ZM = "Zambia",
  ZW = "Zimbabwe",
}

export enum nationalitePays {
  AFG = 'Afghane',
  ALB = 'Albanaise',
  DZA = 'Algérienne',
  AND = 'Andorrane',
  AGO = 'Angolaise',
  AIA = 'Anguillaise',
  ATG = 'Antiguaise',
  ARG = 'Argentine',
  ARM = 'Arménienne',
  ABW = 'Arubaïenne',
  AUS = 'Australienne',
  AUT = 'Autrichienne',
  AZE = 'Azerbaïdjanaise',
  BHS = 'Bahamienne',
  BHR = 'Bahreïnienne',
  BGD = 'Bangladaise',
  BRB = 'Barbadienne',
  BLR = 'Biélorusse',
  BEL = 'Belge',
  BLZ = 'Bélizienne',
  BEN = 'Béninoise',
  BMU = 'Bermudienne',
  BTN = 'Bhoutanaise',
  BOL = 'Bolivienne',
  BIH = 'Bosniaque',
  BWA = 'Botswanaise',
  BRA = 'Brésilienne',
  BRN = 'Brunéienne',
  BGR = 'Bulgare',
  BFA = 'Burkinabée',
  BDI = 'Burundaise',
  KHM = 'Cambodgienne',
  CMR = 'Camerounaise',
  CAN = 'Canadienne',
  CPV = 'Cap-verdienne',
  CYM = 'Caïmanienne',
  CAF = 'Centrafricaine',
  CHL = 'Chilienne',
  CHN = 'Chinoise',
  CYP = 'Chypriote',
  COL = 'Colombienne',
  COM = 'Comorienne',
  COG = 'Congolaise',
  COD = 'Congolaise (République démocratique)',
  CRI = 'Costaricaine',
  HRV = 'Croate',
  CUB = 'Cubaine',
  CUW = 'Curacienne',
  DNK = 'Danoise',
  DJI = 'Djiboutienne',
  DMA = 'Dominicaine',
  DOM = 'Dominicaine (République)',
  ECU = 'Équatorienne',
  EGY = 'Égyptienne',
  SLV = 'Salvadorienne',
  AREM = 'Émirienne',
  GNQ = 'Équato-guinéenne',
  ERI = 'Érythréenne',
  ESP = 'Espagnole',
  EST = 'Estonienne',
  ETH = 'Éthiopienne',
  FLK = 'Malouine',
  FRO = 'Féroïenne',
  FJI = 'Fidjienne',
  FIN = 'Finlandaise',
  FRA = 'Française',
  GAB = 'Gabonaise',
  GMB = 'Gambienne',
  GEO = 'Géorgienne',
  DEU = 'Allemande',
  GHA = 'Ghanéenne',
  GIB = 'Gibraltarienne',
  GRC = 'Grecque',
  GRL = 'Groenlandaise',
  GRD = 'Grenadienne',
  GLP = 'Guadeloupéenne',
  GUM = 'Guamienne',
  GTM = 'Guatémaltèque',
  GGY = 'Guernesiaise',
  GIN = 'Guinéenne',
  GNB = 'Bissau-Guinéenne',
  GUY = 'Guyanienne',
  HTI = 'Haïtienne',
  HND = 'Hondurienne',
  HKG = 'Hongkongaise',
  HUN = 'Hongroise',
  ISL = 'Islandaise',
  IND = 'Indienne',
  IDN = 'Indonésienne',
  IRN = 'Iranienne',
  IRQ = 'Irakienne',
  IRL = 'Irlandaise',
  ISR = 'Israélienne',
  ITA = 'Italienne',
  CIV = 'Ivoirienne',
  JAM = 'Jamaïcaine',
  JPN = 'Japonaise',
  JEY = 'Jerseyaise',
  JOR = 'Jordanienne',
  KAZ = 'Kazakhe',
  KEN = 'Kényane',
  KIR = 'Kiribatienne',
  PRK = 'Nord-Coréenne',
  KOR = 'Sud-Coréenne',
  KWT = 'Koweïtienne',
  KGZ = 'Kirghize',
  LAO = 'Laotienne',
  LVA = 'Lettone',
  LBN = 'Libanaise',
  LSO = 'Lesothane',
  LBR = 'Libérienne',
  LBY = 'Libyenne',
  LIE = 'Liechtensteinoise',
  LTU = 'Lituanienne',
  LUX = 'Luxembourgeoise',
  MAC = 'Macanaise',
  MDG = 'Malgache',
  MWI = 'Malawite',
  MYS = 'Malaisienne',
  MDV = 'Maldivienne',
  MLT = 'Maltaise',
  MHL = 'Marshallaise',
  MRT = 'Mauritanienne',
  MUS = 'Mauricienne',
  MEX = 'Mexicaine',
  FSM = 'Micronésienne',
  MDA = 'Moldave',
  MCO = 'Monégasque',
  MNG = 'Mongole',
  MNE = 'Monténégrine',
  MSR = 'Montserratienne',
  MAR = 'Marocaine',
  MOZ = 'Mozambicaine',
  MMR = 'Birmane',
  NAM = 'Namibienne',
  NRU = 'Nauruane',
  NPL = 'Népalaise',
  NLD = 'Néerlandaise',
  NCL = 'Néo-Calédonienne',
  NZL = 'Néo-Zélandaise',
  NIC = 'Nicaraguayenne',
  NER = 'Nigérienne',
  NGA = 'Nigériane',
  NIU = 'Niuevienne',
  MNP = 'Mariannes du Nord',
  MKD = 'Macédonienne',
  NOR = 'Norvégienne',
  OMN = 'Omanaise',
  PAK = 'Pakistanaise',
  PLW = 'Palaosienne',
  PAN = 'Panaméenne',
  PNG = 'Papouane-Néo-Guinéenne',
  PRY = 'Paraguayenne',
  PER = 'Péruvienne',
  PHL = 'Philippine',
  PCN = 'Pittoresque',
  POL = 'Polonaise',
  PRT = 'Portugaise',
  PRI = 'Portoricaine',
  QAT = 'Qatarienne',
  REU = 'Réunionnaise',
  ROU = 'Roumaine',
  RUS = 'Russe',
  RWA = 'Rwandaise',
  SHN = 'Sainte-Hélène',
  KNA = 'Kittsienne et Névicienne',
  LCA = 'Sainte-Lucienne',
  SPM = 'Saint-Pierraise et Miquelonnaise',
  VCT = 'Saint-Vincentaise et Grenadine',
  WSM = 'Samoane',
  SMR = 'Saint-Marinaise',
  STP = 'Santoméenne',
  SAU = 'Saoudienne',
  SEN = 'Sénégalaise',
  SRB = 'Serbe',
  SYC = 'Seychelloise',
  SLE = 'Sierra-Léonaise',
  SGP = 'Singapourienne',
  SVK = 'Slovaque',
  SVN = 'Slovène',
  SLB = 'Salomonaise',
  SOM = 'Somalienne',
  ZAF = 'Sud-Africaine',
  SSD = 'Sud-Soudanaise',
  ESPA = 'Espagnole',
  LKA = 'Sri-Lankaise',
  SDN = 'Soudanaise',
  SUR = 'Surinamaise',
  SWE = 'Suédoise',
  CHE = 'Suisse',
  SYR = 'Syrienne',
  TWN = 'Taïwanaise',
  TJK = 'Tadjike',
  TZA = 'Tanzanienne',
  THA = 'Thaïlandaise',
  TLS = 'Timoraise',
  TGO = 'Togolaise',
  TON = 'Tonguienne',
  TTO = 'Trinidadienne',
  TUN = 'Tunisienne',
  TUR = 'Turque',
  TKM = 'Turkmène',
  TCA = 'Turc et Caïcos',
  TUV = 'Tuvaluane',
  UGA = 'Ougandaise',
  UKR = 'Ukrainienne',
  AREN = 'Émirienne',
  GBR = 'Britannique',
  USA = 'Américaine',
  URY = 'Uruguayenne',
  UZB = 'Ouzbéke',
  VUT = 'Vanuatuane',
  VEN = 'Vénézuélienne',
  VNM = 'Vietnamienne',
  VGB = 'Vierges britanniques',
  VIR = 'Vierges américaines',
  WLF = 'Wallisienne et Futunienne',
  YEM = 'Yéménite',
  ZMB = 'Zambienne',
  ZWE = 'Zimbabwéenne',
}
